apiVersion: apps/v1
kind: Deployment
metadata:
  name: pl
  labels:
    app: dashboard
spec:
  selector:
    matchLabels:
      app: dashboard
  replicas: 3
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - name: dashboard
        image: 192.168.1.10:8443/library/dashboard
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
